#!/bin/bash

#
# Build UI with npm
# Requires:
# - libpam0g-dev on Ubuntu
# - pam-devel on Fedora
#

# Exit 1 on error
set -xe

# Prepare dist
mkdir -p dist

#
# Clean old versions
#
rm -rf dist/ui.tar.gz
rm -rf dist/api
rm -rf dist/tasks

#
# Build UI
#
pushd ui
buildah build --rm --layers --jobs "$(nproc)" --tag nethesis/nethvoice-report-ui
dist_container="$(podman run --rm -d nethesis/nethvoice-report-ui:latest tail -f /dev/null)"
podman cp "$dist_container":/app/dist dist
podman stop -t 0 "$dist_container"
tar cvzf ui.tar.gz -C dist .
cp ui.tar.gz ../dist/
popd

#
# Build API
#
pushd api
unset GOPATH
GO111MODULE=on
go build
cp api ../dist/
popd

#
# Build Tasks
#
pushd tasks
unset GOPATH
GO111MODULE=on
go build
cp tasks ../dist/
popd
