#!/bin/bash

#
# Build UI with npm
# Requires:
# - libpam0g-dev on Ubuntu
# - pam-devel on Fedora
#

# Exit 1 on error
set -xe

# Prepare dist
mkdir -p dist

#
# Clean old versions
#
rm -rf dist/ui.tar.gz
rm -rf dist/api
rm -rf dist/tasks

#
# Build UI
#
pushd ui
rm -rf dist/
npm install
NODE_ENV=production npm run build
tar cvzf ui.tar.gz -C dist .
cp ui.tar.gz ../dist/
popd

#
# Build API
#
pushd api
unset GOPATH
GO111MODULE=on
go build
cp api ../dist/
popd

#
# Build Tasks
#
pushd tasks
unset GOPATH
GO111MODULE=on
go build
cp tasks ../dist/
popd
