#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

password=$(perl -e "use NethServer::Password; print NethServer::Password::store('nethvoice_report');")

# create schema
/usr/bin/mysql --defaults-file=/root/.my.cnf asteriskcdrdb < /opt/nethvoice-report/scripts/schema.sql

# grant some accesses to asteriskcdrdb database
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT SELECT on asteriskcdrdb.* to 'nethvoice_report'@'localhost' identified by '$password';"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT INSERT on asteriskcdrdb.* to 'nethvoice_report'@'localhost' identified by '$password';"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT CREATE on asteriskcdrdb.* to 'nethvoice_report'@'localhost' identified by '$password';"
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT DROP on asteriskcdrdb.* to 'nethvoice_report'@'localhost' identified by '$password';"

# grant read access to phonebook database
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT SELECT on phonebook.* to 'nethvoice_report'@'localhost' identified by '$password';"

# flush privileges
/usr/bin/mysql --defaults-file=/root/.my.cnf -e "FLUSH PRIVILEGES"

# precalculate some data to use report immediately
/opt/nethvoice-report/tasks/tasks views
/opt/nethvoice-report/tasks/tasks phonebook
/opt/nethvoice-report/tasks/tasks values
