FROM docker.io/golang:1.18.10
# Setup image
WORKDIR /app
RUN apt-get update \
    && apt-get install -y librrd-dev libpam0g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Download dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download
# Build the binary
COPY . .
RUN go build
